### ISSUE TITLE
Creating config backup fails

### ISSUE THREAD

**Issue by BlueVulture** [YveOne/GDMultiStash#1]
https://github.com/YveOne/GDMultiStash/blob/095acfb08428ae1d2d3edba3c7960485ed27b4e2/GDMultiStash/GlobalHandlers/ConfigurationHandler.cs#L172

This line should have a third parameter to overwrite an existing backup, otherwise it crashes.

![image](https://github.com/YveOne/GDMultiStash/assets/28387000/eac6da84-da1a-4885-aa49-2e2c9e87b80a)

Removing the backup does work.

Good day.

**Comment by YveOne** [comment]
Thank you. It has been solved now in v1.39.4

**Comment by Vonny1412** [comment]
Thank you. It has been solved now in v1.39.4
Gonna close this issue later after checking that there isn't any other problem with the backup
